EMULATOR = /Users/timger/Library/Android/sdk/tools/emulator


clean:
	./gradlew clean


sync:
	./gradlew sync

build:
	./gradlew assemble


push:
	git commit -a -m 'init'
	git push origin master



open:
	open app/build/outputs/apk/debug

